version: '3.4'
services:
  webserver:
    image: nginx:latest
    container_name: webserver
    restart: always
    ports: 
    - "8080:80"
    depends_on:
          - database
  database:
    image: mysql
    container_name: database    
    environment:
     - MYSQL_ALLOW_EMPTY_PASSWORD=yes
     - MYSQL_DATABASE= atividade3
    ports: 
     - "3306:3306"
