version: '3.4'
services:
  webserver:
    image: nginx:latest
    container_name: webserver
    restart: always
    ports: 
    - "8080:80"
    depends_on:
          - db
  db:
    image: mysql
    container_name: db     
    environment:
     - MYSQL_USER=root
     - MYSQL_ALLOW_EMPTY_PASSWORD=yes
     - MYSQL_DATABASE=loja
